/**
 * cheias.pt — Declarative chapter definitions
 *
 * Each chapter defines: text content, camera position, animation,
 * layer visibility, legend items, and alignment.
 */

export const chapters = [
  {
    id: 'chapter-0',
    title: 'O Inverno Que Partiu os Rios',
    subtitle: 'Como três tempestades expuseram a fragilidade de Portugal',
    byline: 'cheias.pt · Uma história contada com dados de satélite e modelos hidrológicos',
    text: null,
    alignment: 'fully',
    camera: { center: [-15, 35], zoom: 3, pitch: 0, bearing: 0 },
    animation: { type: 'flyTo', duration: 0 },
    layers: [],
    legend: [],
    source: null,
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-1',
    title: '7 de Fevereiro de 2026',
    subtitle: null,
    text: 'O satélite Sentinel-1 capturou esta imagem. O vermelho é água onde antes havia terra. O Tejo atingiu o nível mais alto desde 1997. 11 pessoas morreram. 69 municípios declararam calamidade.',
    alignment: 'left',
    camera: { center: [-8.5, 39.5], zoom: 6.5, pitch: 15, bearing: 5 },
    animation: { type: 'flyTo', duration: 3000 },
    layers: [
      { id: 'sentinel1-flood-extent', opacity: 0.8, type: 'geojson' },
      { id: 'portugal-outline', opacity: 0.3, type: 'geojson' },
    ],
    legend: [{ title: 'Área inundada', color: '#e74c3c', type: 'fill' }],
    source: 'Dados: Copernicus Sentinel-1 / CEMS Rapid Mapping (EMSR864)',
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-2',
    title: 'A Energia do Atlântico',
    subtitle: null,
    text: 'O inverno de 2025-26 trouxe uma energia incomum ao Atlântico Norte. Temperaturas da superfície do mar acima da média alimentaram uma sequência de tempestades: Harry, Ingrid, Joseph, Kristin, Leonardo, Marta. Cada uma carregou mais humidade do que a anterior — humidade que viajou milhares de quilómetros até embater na costa portuguesa.',
    alignment: 'right',
    camera: { center: [-30, 30], zoom: 3, pitch: 0, bearing: 0 },
    animation: { type: 'flyTo', duration: 2500 },
    layers: [
      { id: 'sst-anomaly', opacity: 0.7, type: 'raster' },
      { id: 'atmospheric-river-track', opacity: 0.9, type: 'line' },
    ],
    legend: [],
    source: 'Dados: NOAA SST Anomalies / ERA5 Reanalysis',
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-3',
    title: 'O Solo Encharca',
    subtitle: null,
    text: 'Antes de qualquer tempestade, o solo já estava a encher. Semanas de chuva persistente saturaram os primeiros 30 centímetros de terra — a camada que absorve a chuva e impede cheias. Quando Kristin chegou em Janeiro, o solo já não tinha para onde mandar a água. Cada gota adicional ia directamente para os rios.',
    alignment: 'left',
    camera: { center: [-8.3, 39.8], zoom: 7, pitch: 20, bearing: -5 },
    animation: { type: 'flyTo', duration: 2000 },
    layers: [
      { id: 'soil-moisture-animation', opacity: 0.8, type: 'circle' },
      { id: 'basins-outline', opacity: 0.4, type: 'geojson' },
    ],
    legend: [
      { title: 'Solo seco', color: '#f7f7f7', type: 'fill' },
      { title: 'Solo saturado', color: '#2166ac', type: 'fill' },
    ],
    source: 'Dados: Open-Meteo / ERA5-Land Soil Moisture (0-30cm)',
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-4',
    title: 'Três Tempestades em Duas Semanas',
    subtitle: null,
    text: 'Kristin atingiu a costa a 29 de Janeiro com ventos de força de furacão — possivelmente a tempestade mais forte desde que há registos. Antes que os rios baixassem, Leonardo chegou a 6 de Fevereiro, despejando o equivalente a três dias de chuva em 24 horas. Marta seguiu-se dias depois. Na zona de Grazalema, em Espanha, caíram mais de 500mm num único dia.',
    alignment: 'right',
    camera: { center: [-8.5, 39.5], zoom: 7.5, pitch: 25, bearing: 10 },
    animation: { type: 'easeTo', duration: 1500 },
    layers: [
      { id: 'precipitation-accumulation', opacity: 0.8, type: 'circle' },
      { id: 'ipma-warnings-timeline', opacity: 0.9, type: 'geojson' },
      { id: 'basins-outline', opacity: 0.3, type: 'geojson' },
    ],
    legend: [
      { title: '> 250mm', color: '#e74c3c', type: 'fill' },
      { title: '100–250mm', color: '#F7991F', type: 'fill' },
      { title: '50–100mm', color: '#f7f7b5', type: 'fill' },
      { title: '< 50mm', color: '#2166ac', type: 'fill' },
    ],
    source: 'Dados: Open-Meteo / ERA5 Precipitation / IPMA',
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-5',
    title: 'Os Rios Respondem',
    subtitle: null,
    text: 'O Tejo. O Mondego. O Sado. Cada rio carrega a história do seu território — a chuva que caiu, o solo que não absorveu, as descargas das barragens espanholas a montante. O caudal do Tejo atingiu o nível mais alto em quase 30 anos. O Sado voltou a valores de 1989. Em Coimbra, o dique do Mondego cedeu.',
    alignment: 'left',
    camera: { center: [-8.4, 39.6], zoom: 8, pitch: 30, bearing: -10 },
    animation: { type: 'easeTo', duration: 1200 },
    layers: [
      { id: 'glofas-discharge', opacity: 0.9, type: 'circle' },
      { id: 'basins-fill', opacity: 0.4, type: 'geojson' },
      { id: 'soil-moisture-snapshot', opacity: 0.3, type: 'circle' },
    ],
    legend: [
      { title: 'Caudal excepcional', color: '#e74c3c', type: 'fill' },
      { title: 'Caudal elevado', color: '#F7991F', type: 'fill' },
      { title: 'Caudal normal', color: '#2166ac', type: 'fill' },
    ],
    source: 'Dados: GloFAS / Open-Meteo Flood API',
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-6',
    title: 'O Custo Humano',
    subtitle: null,
    text: null,
    alignment: 'left',
    camera: { center: [-8.52, 38.37], zoom: 12, pitch: 40, bearing: 15 },
    animation: { type: 'flyTo', duration: 2000 },
    layers: [
      { id: 'flood-extent-polygons', opacity: 0.7, type: 'geojson' },
      { id: 'consequence-markers', opacity: 1.0, type: 'geojson' },
      { id: 'satellite-after', opacity: 0.6, type: 'raster' },
    ],
    legend: [
      { title: 'Mortes', color: '#e74c3c', type: 'circle' },
      { title: 'Evacuações', color: '#F7991F', type: 'circle' },
      { title: 'Infraestrutura', color: '#8e44ad', type: 'circle' },
      { title: 'Deslizamentos', color: '#795548', type: 'circle' },
    ],
    source: 'Dados: CEMS Rapid Mapping (EMSR861, EMSR864)',
    substeps: [
      {
        id: 'chapter-6a',
        title: 'Alcácer do Sal',
        text: 'A água do Sado subiu dois metros no centro da vila. Moradores descreveram uma calamidade que não viam há 30 anos.',
        alignment: 'left',
        camera: { center: [-8.52, 38.37], zoom: 12, pitch: 40, bearing: 15 },
        animation: { type: 'flyTo', duration: 2000 },
      },
      {
        id: 'chapter-6b',
        title: 'Coimbra',
        text: 'O dique do Mondego cedeu em Casais. 3.000 pessoas evacuadas numa noite. Campos agrícolas submersos em todas as direcções.',
        alignment: 'right',
        camera: { center: [-8.43, 40.21], zoom: 11, pitch: 35, bearing: -10 },
        animation: { type: 'flyTo', duration: 2500 },
      },
      {
        id: 'chapter-6c',
        title: 'A Autoestrada',
        text: 'A principal auto-estrada do país colapsou perto de Coimbra. A artéria Norte-Sul de Portugal, cortada.',
        alignment: 'left',
        camera: { center: [-8.487, 40.217], zoom: 13, pitch: 45, bearing: 5 },
        animation: { type: 'flyTo', duration: 2000 },
      },
    ],
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-7',
    title: 'A Cadeia Causal',
    subtitle: null,
    text: 'Solo saturado. Chuva intensa. Rios que ultrapassaram os limites. E por baixo de tudo, incêndios do verão anterior que tinham arrancado a vegetação que segurava as encostas. Cada peça sozinha era gerível. Juntas, criaram uma catástrofe.',
    alignment: 'fully',
    camera: { center: [-8.2, 39.5], zoom: 7, pitch: 20, bearing: 0 },
    animation: { type: 'flyTo', duration: 2000 },
    layers: [
      { id: 'basins-fill', opacity: 0.6, type: 'geojson' },
      { id: 'flood-extent-polygons', opacity: 0.5, type: 'geojson' },
      { id: 'consequence-markers', opacity: 0.8, type: 'geojson' },
      { id: 'precipitation-accumulation', opacity: 0.3, type: 'circle' },
    ],
    legend: [
      { title: 'Risco crítico', color: '#b2182b', type: 'fill' },
      { title: 'Risco elevado', color: '#ef8a62', type: 'fill' },
      { title: 'Risco moderado', color: '#f7f7f7', type: 'fill' },
      { title: 'Risco baixo', color: '#2166ac', type: 'fill' },
    ],
    source: null,
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-8',
    title: 'O Que os Dados Já Sabiam',
    subtitle: null,
    text: 'O índice de pré-condição de cheia combina três sinais: humidade do solo, precipitação prevista, e caudal nos rios. Duas semanas antes de Kristin, este índice mostrava grande parte de Portugal centro e sul em condições de risco elevado. Portugal não tem um sistema nacional de previsão de cheias. O SVARH observa, mas não prevê. O EFAS europeu tem capacidade degradada para rios portugueses regulados por barragens. Uma plataforma aberta, baseada em dados públicos, poderia ter dado mais tempo para preparar.',
    alignment: 'left',
    camera: { center: [-8.3, 39.5], zoom: 6.5, pitch: 10, bearing: 0 },
    animation: { type: 'flyTo', duration: 1500 },
    layers: [
      { id: 'basins-fill', opacity: 0.5, type: 'geojson' },
    ],
    legend: [
      { title: 'Risco crítico', color: '#b2182b', type: 'fill' },
      { title: 'Risco elevado', color: '#ef8a62', type: 'fill' },
      { title: 'Risco moderado', color: '#f7f7f7', type: 'fill' },
      { title: 'Risco baixo', color: '#2166ac', type: 'fill' },
    ],
    source: null,
    onEnter: null,
    onLeave: null,
  },
  {
    id: 'chapter-9',
    title: 'Explorar os Dados',
    subtitle: null,
    text: 'Os dados por detrás desta história são públicos e abertos. Explore o mapa, clique nas bacias hidrográficas, veja os dados para a sua zona.',
    alignment: 'fully',
    camera: { center: [-8.0, 39.5], zoom: 6, pitch: 0, bearing: 0 },
    animation: { type: 'flyTo', duration: 1500 },
    layers: [],
    legend: [],
    source: null,
    cta: [
      { label: 'Ver a minha zona', action: 'geolocate' },
      { label: 'Metodologia', action: 'methodology' },
      { label: 'Partilhar', action: 'share' },
    ],
    onEnter: 'enableExploration',
    onLeave: 'disableExploration',
  },
];
